export const GET_ORDERS = 'GET_ORDERS'
export const ORDERS_LOADING = 'ORDERS_LOADING'
export const GET_ITEMS = 'GET_ITEMS' 
export const ITEMS_LOADING = 'ITEMS_LOADING'
export const UPDATE_ORDER = 'UPDATE_ORDER'
export const ADD_ORDER = 'ADD_ORDER'